In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
college_data = pd.read_csv('data/MERGED2017_18_PP.csv', low_memory = False) # Opens our data into a dataframe
college_data.shape

(7112, 1977)

In [3]:
college_data = college_data.dropna(axis = 1, how= 'all')
college_data.shape

(7112, 648)

In [4]:
college_data[college_data.columns] = college_data[college_data.columns].apply(pd.to_numeric, errors='coerce')


In [5]:
college_data = college_data.fillna(college_data.median())  # works


In [6]:
college_data.shape

(7112, 648)

In [7]:
college_data = college_data.dropna(axis = 1, how= 'all')

for column in college_data.columns:
    print(column)
    print(college_data[column].unique())

UNITID
[  100654   100663   100690 ... 48400201 48778201 49005401]
OPEID
[ 100200  105200 2503400 ... 4228101 4221501 4182601]
OPEID6
[ 1002  1052 25034 ... 42659 42671 42663]
ZIP
[3.57620000e+04 4.80910000e+04 3.58990000e+04 ... 9.35340000e+08
 2.14800000e+07 3.33137268e+08]
HCM2
[0 1]
MAIN
[1 0]
NUMBRANCH
[ 1 15  3 11  4 10  6  2 21 14  5 12 13 26 33  9  7  8 73 17 18 23 34]
PREDDEG
[3 2 1 4 0]
HIGHDEG
[4 2 3 1 0]
CONTROL
[1 2 3]
ST_FIPS
[ 1  2 53  4 35  5  6 27  8  9 36 10 11 12 13 15 16 17 18 26 19 20 29 21
 22 23 24 25 28 30 31 32 33 34 37 38 39 54 40 41 42 44 45 46 47 48 49 50
 51 55 56 60 66 69 72 64 70 78 68]
REGION
[5 8 6 0 4 7 1 2 3 9]
LOCALE
[12. 32. 31. 13. 41. 21. 43. 42. 33. 11. 23. 22. -3.]
LATITUDE
[34.783368 33.505697 32.362609 ... 42.645603 32.834122 38.792443]
LONGITUDE
[-86.568502 -86.799345 -86.17401  ... -87.855007 -97.196111 -86.337037]
CCBASIC
[18. 15. 20. 16. 19.  2. 22. 21.  1. 23.  5.  7. -2. 24.  8.  4. 17. 32.
 13. 10. 26. 30.  9.  6. 33. 11.  3. 29. 25. 12

 1.395e-01 1.204e-01 4.230e-02 3.810e-02]
PCIP46
[0.000e+00 1.530e-02 3.110e-02 7.000e-04 1.607e-01 2.020e-02 2.144e-01
 2.670e-02 2.630e-02 2.470e-02 2.100e-02 5.510e-02 1.080e-02 2.830e-02
 1.880e-02 8.800e-03 1.025e-01 6.800e-03 1.391e-01 3.240e-02 1.140e-02
 1.750e-02 5.090e-02 1.200e-03 2.800e-03 2.850e-02 9.900e-03 8.300e-03
 4.830e-02 7.300e-03 3.290e-02 2.380e-02 4.980e-02 3.960e-02 2.240e-02
 6.900e-03 7.200e-03 1.100e-02 8.600e-03 2.340e-01 3.495e-01 2.179e-01
 1.301e-01 3.667e-01 2.885e-01 1.350e-02 4.400e-03 9.500e-03 1.800e-03
 9.300e-03 8.400e-03 3.600e-03 2.400e-03 6.860e-02 1.100e-03 7.400e-03
 4.637e-01 2.000e-03 3.190e-02 9.600e-02 4.000e-04 5.100e-03 1.610e-02
 1.400e-02 2.650e-02 3.050e-02 2.600e-02 1.400e-03 5.290e-02 1.060e-02
 3.100e-03 2.230e-02 4.100e-03 3.500e-03 5.300e-03 3.200e-03 4.000e-03
 2.390e-02 1.160e-02 1.459e-01 2.660e-02 4.380e-02 4.640e-02 1.168e-01
 1.294e-01 6.510e-02 1.674e-01 2.077e-01 5.840e-02 4.200e-03 2.700e-03
 7.650e-02 1.490e-02 8.000e-

 177. 305.]
NUM43_PUB
[ 88. 173.  38.  46. 176.  11.  59. 151.   0.  26. 107.  55.  37.  41.
   1.   5. 142.   7.  86.  80.  35.  10.  65. 148.  16.  23.  18. 194.
  15.  29. 113.   9. 493.  44. 352.  48.  19. 432.  67. 156.  39.  28.
  77. 241.  71. 153. 219. 259.  14.  21.  31.  13.  50.  47.  70. 127.
  87.  81. 131.   8.  12. 189. 179. 191. 422. 441. 271. 160. 356. 488.
 196. 537. 409. 449. 500. 311. 494. 594. 479. 778. 468. 367. 411.  75.
   2.   6.  22.  32.  82. 116. 132. 103.   3. 167.  24.  66.  40.   4.
  69. 164.  83.  33.  79.  74. 302. 380. 136. 359.  20.  62. 134.  45.
 161. 100.  56.  30. 129. 172. 273.  34. 334. 123. 217. 168.  42. 220.
  91.  58.  51. 146.  99. 205. 180. 354. 545. 139. 258. 149. 459. 382.
 135.  49. 330. 187. 141.  73. 157. 215. 407. 118.  61. 130. 140.  57.
 361. 439. 362.  43. 304. 137.  85. 169.  78.  64. 101. 418. 532. 350.
  25.  17.  96.  68. 144. 235.  76.  60. 190.  53. 447. 389. 198. 491.
 210. 120.  52. 105. 233. 228.  94. 346. 260.  27. 122.

[9.0000e+01 3.8800e+02 3.3700e+02 3.1600e+02 9.6400e+02 1.0440e+03
 8.7000e+01 8.5500e+02 9.3300e+02 3.8300e+02 1.4500e+02 2.6600e+02
 2.5400e+02 1.0960e+03 1.2590e+03 6.4900e+02 4.4600e+02 2.7600e+02
 6.8500e+02 5.3400e+02 4.2900e+02 7.9000e+01 6.7500e+02 7.1900e+02
 7.0700e+02 2.2900e+02 7.5700e+02 3.9400e+02 4.5200e+02 5.3000e+01
 3.5400e+02 3.5900e+02 2.1100e+02 2.1200e+02 1.1000e+01 7.5600e+02
 7.8200e+02 5.3600e+02 6.0000e+01 5.5300e+02 3.3000e+01 2.7000e+01
 5.6000e+01 1.4900e+02 4.6800e+02 1.9810e+03 3.0200e+02 1.8360e+03
 2.1500e+02 5.6900e+02 7.2000e+01 7.4200e+02 2.5000e+01 2.4480e+03
 8.0000e+02 6.2400e+02 1.1300e+02 2.1000e+01 2.3000e+01 8.4700e+02
 3.9000e+02 9.8700e+02 6.1000e+01 5.6100e+02 1.0000e+00 2.0000e+01
 2.2000e+01 6.0500e+02 4.7000e+01 2.9800e+02 1.8400e+02 2.0200e+02
 3.8100e+02 1.2000e+02 3.6400e+02 2.3100e+02 9.0000e+00 1.7400e+02
 3.5000e+01 1.8500e+02 4.0000e+01 2.3800e+02 1.8900e+02 4.0000e+02
 1.4800e+02 1.9300e+02 1.3000e+01 2.2300e+02 1.6000e+01 3.6000

 0.8615 0.6829 0.55   0.8857 0.8276 0.4103 0.7975 0.9694 0.4462]
D150_L4_LOANNOPELL
[  9.  28.  10.  11.  87.  55.  23.   5.  80.  44.  82.  12.   2.  50.
   3.  85.  29.  35.  95.  15. 135. 102.  36. 112.  53.  67.   4.  63.
  16. 186.   1.  21.  24.  37.  17.   7.  22.   6.  30.   8.  32.  26.
  58.  33.  25.  38.  83.  59.  13. 134. 100. 103. 120.  89.  52.  19.
  18. 116.  47.  64. 176.  62.  14.  41.  20. 173. 108. 237.  49.  42.
  86.  60. 327. 158.  27. 267.  43. 124. 113. 147.  54. 142. 262.  34.
  65.  98.  45. 136.  48.  74.  39. 277.  70.  66.  69. 118. 104. 117.
  88.  46.  97.  75. 202. 148.  77.  73. 133.  90.  78.  84.  56. 122.
  57. 145.  31. 157.  40. 170. 131. 187.  72. 137.  79. 168. 140. 105.
 152.  93.  71. 221.  91.  51. 153. 182. 106. 224. 216. 238. 121.  61.
 115. 110. 179. 167. 109. 150.  94. 127. 235. 249.  99. 175. 214. 165.
 436. 196. 174.  81. 567. 329. 129. 189. 111. 101.  96. 180. 336. 252.
 207. 149. 132. 159. 114.  92. 228. 126.  76. 130.]
C150_4_NOLOA

[1.630e-02 7.860e-02 2.630e-02 2.230e-02 2.510e-02 8.000e-03 1.730e-02
 4.200e-03 1.890e-02 7.200e-03 3.400e-03 6.800e-03 7.900e-03 0.000e+00
 1.080e-02 1.050e-02 9.100e-03 4.140e-02 2.000e-02 1.170e-02 1.990e-01
 4.000e-03 5.500e-03 5.100e-03 2.490e-02 1.200e-02 2.740e-02 1.980e-02
 6.000e-03 1.550e-02 1.500e-03 9.800e-03 2.000e-03 1.100e-03 1.000e-02
 1.440e-02 2.840e-02 8.800e-03 1.760e-02 7.600e-03 9.900e-03 1.400e-03
 2.260e-02 5.250e-02 2.600e-02 6.400e-03 4.980e-01 7.800e-03 1.530e-02
 7.000e-04 1.720e-02 4.640e-02 4.020e-02 1.470e-02 2.400e-03 1.270e-02
 4.150e-02 9.700e-03 1.610e-02 3.150e-02 3.900e-03 1.380e-02 3.710e-02
 1.230e-02 2.560e-02 2.570e-02 3.370e-02 4.060e-02 3.130e-02 1.510e-02
 2.040e-02 1.780e-02 5.600e-03 4.070e-02 4.120e-02 6.500e-03 1.210e-02
 8.300e-03 1.490e-02 1.240e-02 2.400e-02 1.120e-02 1.340e-02 1.370e-02
 2.710e-02 2.600e-03 1.200e-03 3.200e-03 2.590e-02 2.410e-02 1.350e-02
 2.530e-02 2.800e-03 1.450e-02 5.700e-03 1.710e-02 1.390e-02 1.320e-02
 1.620

In [8]:
import os
out_filepath = os.path.join("data", "cleaned_college_data_only_numeric.csv")
college_data.to_csv(out_filepath, index=False)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
salary_data = pd.read_csv('data/FieldOfStudyData1516_1617_PP.csv', low_memory = False) # Opens our data into a dataframe

In [11]:
salary_data = salary_data[~salary_data['MD_EARN_WNE'].isin(['PrivacySuppressed'])] # Remove all rows that contain privacy suppressed
salary_data = salary_data[~salary_data['DEBTMEDIAN'].isin(['PrivacySuppressed'])] # Remove all rows that contain privacy suppressed
salary_data = salary_data[salary_data['CREDDESC'].str.contains('Bachelor')] # Keep all rows that contain bachelor

In [12]:
salary_data['MD_EARN_WNE'] = salary_data['MD_EARN_WNE'].str.extract('(\d+)').astype(int)
salary_data['DEBTMEDIAN'] = salary_data['DEBTMEDIAN'].str.extract('(\d+)').astype(int)

salary_data['BESTVALUE'] = salary_data['MD_EARN_WNE']/salary_data['DEBTMEDIAN']


In [13]:
combined_data = pd.merge(college_data, salary_data, on='UNITID')


In [14]:
combined_data.head()

UNITID   OPEID  OPEID6_x      ZIP  HCM2  MAIN_x  NUMBRANCH  PREDDEG  \
0  100654  100200      1002  35762.0     0       1          1        3   
1  100654  100200      1002  35762.0     0       1          1        3   
2  100654  100200      1002  35762.0     0       1          1        3   
3  100654  100200      1002  35762.0     0       1          1        3   
4  100654  100200      1002  35762.0     0       1          1        3   

   HIGHDEG  CONTROL_x  ...              COUNT  DEBTMEDIAN  DEBTPAYMENT10YR  \
0        4          1  ...                 25       36250              376   
1        4          1  ...                 46       31505              327   
2        4          1  ...                 22       34809              361   
3        4          1  ...  PrivacySuppressed       36928              383   
4        4          1  ...                 39       29956              311   

   DEBTMEAN  TITLEIVCOUNT  EARNINGSCOUNT  MD_EARN_WNE  IPEDSCOUNT1  \
0     37194            33             33        54300         17.0   
1     33085            32             31        25400         24.0   
2     36482            33             31        54500         19.0   
3     38900            24             24        45800         13.0   
4     30970            30             30        24000         28.0   

   IPEDSCOUNT2  BESTVALUE  
0         16.0   1.497931  
1         33.0   0.806221  
2         11.0   1.565687  
3         17.0   1.240251  
4         28.0   0.801175  

[5 rows x 651 columns]

In [15]:
combined_data[combined_data.columns] = combined_data[combined_data.columns].apply(pd.to_numeric, errors='coerce')


In [16]:
combined_data.head()

UNITID   OPEID  OPEID6_x      ZIP  HCM2  MAIN_x  NUMBRANCH  PREDDEG  \
0  100654  100200      1002  35762.0     0       1          1        3   
1  100654  100200      1002  35762.0     0       1          1        3   
2  100654  100200      1002  35762.0     0       1          1        3   
3  100654  100200      1002  35762.0     0       1          1        3   
4  100654  100200      1002  35762.0     0       1          1        3   

   HIGHDEG  CONTROL_x  ...  COUNT  DEBTMEDIAN  DEBTPAYMENT10YR  DEBTMEAN  \
0        4          1  ...   25.0       36250              376   37194.0   
1        4          1  ...   46.0       31505              327   33085.0   
2        4          1  ...   22.0       34809              361   36482.0   
3        4          1  ...    NaN       36928              383   38900.0   
4        4          1  ...   39.0       29956              311   30970.0   

   TITLEIVCOUNT  EARNINGSCOUNT  MD_EARN_WNE  IPEDSCOUNT1  IPEDSCOUNT2  \
0          33.0           33.0        54300         17.0         16.0   
1          32.0           31.0        25400         24.0         33.0   
2          33.0           31.0        54500         19.0         11.0   
3          24.0           24.0        45800         13.0         17.0   
4          30.0           30.0        24000         28.0         28.0   

   BESTVALUE  
0   1.497931  
1   0.806221  
2   1.565687  
3   1.240251  
4   0.801175  

[5 rows x 651 columns]

In [17]:
combined_data = combined_data.fillna(combined_data.median())
combined_data = combined_data.dropna(axis = 1, how= 'all')


In [18]:
combined_data.replace([np.inf, -np.inf], np.nan, inplace=True)
combined_data = combined_data.fillna(combined_data.median())
combined_data = combined_data.dropna(axis = 1, how= 'all')


In [19]:
X = combined_data.loc[:, combined_data.columns != 'MD_EARN_WNE']
y = combined_data[['MD_EARN_WNE']]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [20]:
X_train.head()

UNITID   OPEID  OPEID6_x      ZIP  HCM2  MAIN_x  NUMBRANCH  PREDDEG  \
9090   182634  257200      2572  48091.0     0       1          1        3   
12399  206084  313100      3131  48091.0     0       1          1        3   
8999   181534  255900      2559  48091.0     0       1          1        3   
3840   141486  160500      1605  48091.0     0       1          1        3   
9176   183062  259000      2590  48091.0     0       1          1        3   

       HIGHDEG  CONTROL_x  ...  CREDLEV  COUNT  DEBTMEDIAN  DEBTPAYMENT10YR  \
9090         3          2  ...        3   69.0       27000              280   
12399        4          1  ...        3   46.0       25786              268   
8999         4          1  ...        3   29.0       23983              249   
3840         4          2  ...        3   26.0       23517              244   
9176         4          1  ...        3   39.0       25772              267   

       DEBTMEAN  TITLEIVCOUNT  EARNINGSCOUNT  IPEDSCOUNT1  IPEDSCOUNT2  \
9090    25880.0          30.0           30.0         28.0         21.0   
12399   27945.0          46.0           46.0         37.0         30.0   
8999    22845.0          23.0           23.0         24.0         12.0   
3840    21276.0          34.0           31.0         36.0         26.0   
9176    23717.0          31.0           31.0         26.0         26.0   

       BESTVALUE  
9090    1.188889  
12399   2.094160  
8999    1.434349  
3840    1.807203  
9176    1.548192  

[5 rows x 646 columns]

In [21]:
from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, NuSVC, SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression, SGDClassifier
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, RandomForestClassifier


# models = [
#     SVC(gamma='auto'), NuSVC(gamma='auto'), LinearSVC(),
#     SGDClassifier(max_iter=100, tol=1e-3), KNeighborsClassifier(),
#     LogisticRegression(solver='lbfgs'), LogisticRegressionCV(cv=3),
#     BaggingClassifier(), ExtraTreesClassifier(n_estimators=300),
#     RandomForestClassifier(n_estimators=300)
# ]


# def score_model(X, y, estimator, **kwargs):
#     """
#     Test various estimators.
#     """
#     y = LabelEncoder().fit_transform(y)

#     # Instantiate the classification model and visualizer
#     model.fit(X, y, **kwargs)

#     expected  = y
#     predicted = model.predict(X)

#     # Compute and return F1 (harmonic mean of precision and recall)
#     print("{}: {}".format(estimator.__class__.__name__, f1_score(expected, predicted)))

# for model in models:
#     print(model)
#     score_model(X_train, y_train, model)

In [22]:
# models = [KNeighborsClassifier()]

# for model in models:
#     print(model)
#     model.fit(X_train, y_train)
#     expected = y_train
#     predicted = model.predict(X_train)
#     print("{}: {}".format(estimator.__class__.__name__, f1_score(expected, predicted)))


In [24]:
from sklearn import model_selection
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

models = []
seed = 7
# models.append(('LR', LogisticRegression()))
# models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
# models.append(('CART', DecisionTreeClassifier()))
# models.append(('NB', GaussianNB()))
# models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
scoring = 'accuracy'
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, y_train.values.ravel(), cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

/Users/seanbarber/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


KNN: 0.015139 (0.002462)
